[build]
  base = "okuafoadamfo-frontend"  # Important for subdirectory projects
  publish = "okuafoadamfo-frontend/dist"  # Must match Vite's output
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200