[build]
  base = "okuafoadamfo-frontend"
  publish = "dist"  # Changed from "okuafoadamfo-frontend/dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
